Unit tests

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -27,7 +27,7 @@ jobs:
   build:
     strategy:
       matrix:
-        platform: [windows, linux, macos]
+        platform: [windows]
         include:
           - platform: windows
             runsOn: windows-latest
@@ -57,6 +57,17 @@ jobs:
         with:
           java-version: 17
           distribution: 'adopt'
+
+      - name: "Build and run tests"
+        run: |
+          if ! ./gradlew build; then
+            echo "Gradle build failed. Exiting the workflow."
+            exit 1
+          fi
+          if ! ./gradlew allTests; then
+            echo "Gradle test failed. Exiting the workflow."
+            exit 1
+          fi        
 
       - name: "Build app for ${{ matrix.platform }}"
         run: |
